name: 定时发送邮件

on:
  schedule:
    - cron: '0 0 31 10 *'  # 每年10月31日 00:00 (UTC 时间) 执行
    - cron: '0 0 30 11 *'  # 每年11月30日 00:00 (UTC 时间) 执行
    - cron: '0 0 31 12 *'  # 每年12月31日 00:00 (UTC 时间) 执行
    - cron: '0 0 2 1 *'  # 每年1月2日 00:00 (UTC 时间) 执行
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: 测试参数
        if: ${{vars.DEBUG}} == 'true'
        run: |
          echo "EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}"
          echo "RECIPIENT_EMAIL_1: ${{ secrets.RECIPIENT_EMAIL_1 }}"
          echo "RECIPIENT_EMAIL_2: ${{ secrets.RECIPIENT_EMAIL_2 }}"
          echo "RENEW_WEBSITE: ${{ secrets.RENEW_WEBSITE }}"
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}} # 你的 Gmail 邮箱地址
          password: ${{secrets.EMAIL_PASSWORD}} # 你的 Gmail 应用专用密码
          subject: 域名快到期了
          to: ${{secrets.RECIPIENT_EMAIL_1}}, ${{secrets.RECIPIENT_EMAIL_2}}
          from: Github Action（自动发送) # <${{secrets.EMAIL_USERNAME}}>
          body: ${{secrets.RENEW_WEBSITE}} 快要到期了，该赶紧续约了
             # upload build test reports
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jfoa-build-reports-定时发送邮件
          path: .github/workflows/logs
