name: 定时发送邮件

on:
  schedule:
    - cron: '0 0 10 1 *'  # 每年10月1日 00:00 (UTC 时间) 执行
    - cron: '0 0 11 1 *'  # 每年11月1日 00:00 (UTC 时间) 执行
    - cron: '0 0 12 1 *'  # 每年12月1日 00:00 (UTC 时间) 执行
    - cron: '0 0 1 1 *'  # 每年1月1日 00:00 (UTC 时间) 执行
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: 发送邮件
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}} # 你的 Gmail 邮箱地址
          password: ${{secrets.EMAIL_PASSWORD}} # 你的 Gmail 应用专用密码
          subject: 邮件主题
          to: ${{secrets.RECIPIENT_EMAIL_1}}, ${{secrets.RECIPIENT_EMAIL_2}} # 多个收件人，用逗号分隔
          from: ${{secrets.EMAIL_USERNAME}}  # 发件人邮箱 (必须与 username 相同)
          body: 邮件正文